{{- if .Values.neoncart.chatbot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nc-chatbot
  namespace: neoncart
  labels:
    {{- include "aio11y.labels" "nc-chatbot" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "aio11y.selectorLabels" "nc-chatbot" | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
{{- end }}
