{{- if .Values.neoncart.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: neoncart-web
  namespace: neoncart
  labels:
    {{- include "aio11y.labels" "neoncart-web" | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "aio11y.selectorLabels" "neoncart-web" | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
{{- end }}
